# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone', models.CharField(choices=[('1', 'Zone 1'), ('3', 'Zone 3'), ('4', 'Zone 4'), ('5', 'Zone 5'), ('6', 'Zone 6'), ('7', 'Zone 7'), ('8', 'Zone 8'), ('9', 'Zone 9')], max_length=1)),
                ('capacity', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
