# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='features',
            new_name='features1',
        ),
        migrations.AddField(
            model_name='room',
            name='features2',
            field=models.CharField(choices=[('T', 'Television'), ('W', 'Whiteboard'), ('P', 'Projector'), ('C', 'Camera'), ('M', 'Monitors'), ('CM', 'Computer Monitors')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='features3',
            field=models.CharField(choices=[('T', 'Television'), ('W', 'Whiteboard'), ('P', 'Projector'), ('C', 'Camera'), ('M', 'Monitors'), ('CM', 'Computer Monitors')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='features4',
            field=models.CharField(choices=[('T', 'Television'), ('W', 'Whiteboard'), ('P', 'Projector'), ('C', 'Camera'), ('M', 'Monitors'), ('CM', 'Computer Monitors')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
