# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20170628_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='features1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='features2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='features3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
